// Generated by gencpp from file yolo_object_detector/coordinates.msg
// DO NOT EDIT!


#ifndef YOLO_OBJECT_DETECTOR_MESSAGE_COORDINATES_H
#define YOLO_OBJECT_DETECTOR_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_object_detector
{
template <class ContainerAllocator>
struct coordinates_
{
  typedef coordinates_<ContainerAllocator> Type;

  coordinates_()
    : object()
    , x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)  {
    }
  coordinates_(const ContainerAllocator& _alloc)
    : object(_alloc)
    , x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type;
  _object_type object;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _w_type;
  _w_type w;

   typedef double _h_type;
  _h_type h;





  typedef boost::shared_ptr< ::yolo_object_detector::coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_object_detector::coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct coordinates_

typedef ::yolo_object_detector::coordinates_<std::allocator<void> > coordinates;

typedef boost::shared_ptr< ::yolo_object_detector::coordinates > coordinatesPtr;
typedef boost::shared_ptr< ::yolo_object_detector::coordinates const> coordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_object_detector::coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_object_detector::coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_object_detector::coordinates_<ContainerAllocator1> & lhs, const ::yolo_object_detector::coordinates_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_object_detector::coordinates_<ContainerAllocator1> & lhs, const ::yolo_object_detector::coordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_object_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::coordinates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_object_detector::coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57f1576828d14d0938a71ac714487247";
  }

  static const char* value(const ::yolo_object_detector::coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57f1576828d14d09ULL;
  static const uint64_t static_value2 = 0x38a71ac714487247ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_object_detector::coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_object_detector/coordinates";
  }

  static const char* value(const ::yolo_object_detector::coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_object_detector::coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object\n"
"float64 x\n"
"float64 y\n"
"float64 w\n"
"float64 h\n"
;
  }

  static const char* value(const ::yolo_object_detector::coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_object_detector::coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_object_detector::coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_object_detector::coordinates_<ContainerAllocator>& v)
  {
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<double>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_OBJECT_DETECTOR_MESSAGE_COORDINATES_H
