// Generated by gencpp from file yolo_object_detector/MultiObjectData.msg
// DO NOT EDIT!


#ifndef YOLO_OBJECT_DETECTOR_MESSAGE_MULTIOBJECTDATA_H
#define YOLO_OBJECT_DETECTOR_MESSAGE_MULTIOBJECTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yolo_object_detector/coordinates.h>

namespace yolo_object_detector
{
template <class ContainerAllocator>
struct MultiObjectData_
{
  typedef MultiObjectData_<ContainerAllocator> Type;

  MultiObjectData_()
    : objects()  {
    }
  MultiObjectData_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::yolo_object_detector::coordinates_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::yolo_object_detector::coordinates_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> const> ConstPtr;

}; // struct MultiObjectData_

typedef ::yolo_object_detector::MultiObjectData_<std::allocator<void> > MultiObjectData;

typedef boost::shared_ptr< ::yolo_object_detector::MultiObjectData > MultiObjectDataPtr;
typedef boost::shared_ptr< ::yolo_object_detector::MultiObjectData const> MultiObjectDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_object_detector::MultiObjectData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_object_detector::MultiObjectData_<ContainerAllocator1> & lhs, const ::yolo_object_detector::MultiObjectData_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_object_detector::MultiObjectData_<ContainerAllocator1> & lhs, const ::yolo_object_detector::MultiObjectData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_object_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acf6d7f5e28f00c5f92b9bb909386535";
  }

  static const char* value(const ::yolo_object_detector::MultiObjectData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacf6d7f5e28f00c5ULL;
  static const uint64_t static_value2 = 0xf92b9bb909386535ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_object_detector/MultiObjectData";
  }

  static const char* value(const ::yolo_object_detector::MultiObjectData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coordinates[] objects\n"
"\n"
"================================================================================\n"
"MSG: yolo_object_detector/coordinates\n"
"string object\n"
"float64 x\n"
"float64 y\n"
"float64 w\n"
"float64 h\n"
;
  }

  static const char* value(const ::yolo_object_detector::MultiObjectData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiObjectData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_object_detector::MultiObjectData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_object_detector::MultiObjectData_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::yolo_object_detector::coordinates_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_OBJECT_DETECTOR_MESSAGE_MULTIOBJECTDATA_H
