// Generated by gencpp from file yolo_object_detector/ObjectData.msg
// DO NOT EDIT!


#ifndef YOLO_OBJECT_DETECTOR_MESSAGE_OBJECTDATA_H
#define YOLO_OBJECT_DETECTOR_MESSAGE_OBJECTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_object_detector
{
template <class ContainerAllocator>
struct ObjectData_
{
  typedef ObjectData_<ContainerAllocator> Type;

  ObjectData_()
    : object()
    , x(0.0)
    , y(0.0)
    , h(0.0)
    , w(0.0)
    , coordinates()  {
    }
  ObjectData_(const ContainerAllocator& _alloc)
    : object(_alloc)
    , x(0.0)
    , y(0.0)
    , h(0.0)
    , w(0.0)
    , coordinates(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type;
  _object_type object;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _h_type;
  _h_type h;

   typedef double _w_type;
  _w_type w;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _coordinates_type;
  _coordinates_type coordinates;





  typedef boost::shared_ptr< ::yolo_object_detector::ObjectData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_object_detector::ObjectData_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectData_

typedef ::yolo_object_detector::ObjectData_<std::allocator<void> > ObjectData;

typedef boost::shared_ptr< ::yolo_object_detector::ObjectData > ObjectDataPtr;
typedef boost::shared_ptr< ::yolo_object_detector::ObjectData const> ObjectDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_object_detector::ObjectData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_object_detector::ObjectData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_object_detector::ObjectData_<ContainerAllocator1> & lhs, const ::yolo_object_detector::ObjectData_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.h == rhs.h &&
    lhs.w == rhs.w &&
    lhs.coordinates == rhs.coordinates;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_object_detector::ObjectData_<ContainerAllocator1> & lhs, const ::yolo_object_detector::ObjectData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_object_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::ObjectData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::ObjectData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::ObjectData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1697bb930fbdf9f628efe9e7ab39f859";
  }

  static const char* value(const ::yolo_object_detector::ObjectData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1697bb930fbdf9f6ULL;
  static const uint64_t static_value2 = 0x28efe9e7ab39f859ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_object_detector/ObjectData";
  }

  static const char* value(const ::yolo_object_detector::ObjectData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object\n"
"float64 x\n"
"float64 y\n"
"float64 h\n"
"float64 w\n"
"float64[] coordinates\n"
;
  }

  static const char* value(const ::yolo_object_detector::ObjectData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.h);
      stream.next(m.w);
      stream.next(m.coordinates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_object_detector::ObjectData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_object_detector::ObjectData_<ContainerAllocator>& v)
  {
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "h: ";
    Printer<double>::stream(s, indent + "  ", v.h);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    s << indent << "coordinates[]" << std::endl;
    for (size_t i = 0; i < v.coordinates.size(); ++i)
    {
      s << indent << "  coordinates[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.coordinates[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_OBJECT_DETECTOR_MESSAGE_OBJECTDATA_H
