// Generated by gencpp from file yolo_object_detector/StereoData.msg
// DO NOT EDIT!


#ifndef YOLO_OBJECT_DETECTOR_MESSAGE_STEREODATA_H
#define YOLO_OBJECT_DETECTOR_MESSAGE_STEREODATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_object_detector
{
template <class ContainerAllocator>
struct StereoData_
{
  typedef StereoData_<ContainerAllocator> Type;

  StereoData_()
    : object()
    , distance(0.0)  {
    }
  StereoData_(const ContainerAllocator& _alloc)
    : object(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type;
  _object_type object;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::yolo_object_detector::StereoData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_object_detector::StereoData_<ContainerAllocator> const> ConstPtr;

}; // struct StereoData_

typedef ::yolo_object_detector::StereoData_<std::allocator<void> > StereoData;

typedef boost::shared_ptr< ::yolo_object_detector::StereoData > StereoDataPtr;
typedef boost::shared_ptr< ::yolo_object_detector::StereoData const> StereoDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_object_detector::StereoData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_object_detector::StereoData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_object_detector::StereoData_<ContainerAllocator1> & lhs, const ::yolo_object_detector::StereoData_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_object_detector::StereoData_<ContainerAllocator1> & lhs, const ::yolo_object_detector::StereoData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_object_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::StereoData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_object_detector::StereoData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::StereoData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_object_detector::StereoData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::StereoData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_object_detector::StereoData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_object_detector::StereoData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cdbf2e1e849e4bcb4a9b0ed1e65ca0e";
  }

  static const char* value(const ::yolo_object_detector::StereoData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cdbf2e1e849e4bcULL;
  static const uint64_t static_value2 = 0xb4a9b0ed1e65ca0eULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_object_detector::StereoData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_object_detector/StereoData";
  }

  static const char* value(const ::yolo_object_detector::StereoData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_object_detector::StereoData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object\n"
"float32 distance\n"
;
  }

  static const char* value(const ::yolo_object_detector::StereoData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_object_detector::StereoData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StereoData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_object_detector::StereoData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_object_detector::StereoData_<ContainerAllocator>& v)
  {
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_OBJECT_DETECTOR_MESSAGE_STEREODATA_H
