# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yolo_object_detector/MultiStereoData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import yolo_object_detector.msg

class MultiStereoData(genpy.Message):
  _md5sum = "c6ceca52144a9fa61205d857ffcfa332"
  _type = "yolo_object_detector/MultiStereoData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """StereoData[] object_distance

================================================================================
MSG: yolo_object_detector/StereoData
string object
float32 distance
"""
  __slots__ = ['object_distance']
  _slot_types = ['yolo_object_detector/StereoData[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MultiStereoData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_distance is None:
        self.object_distance = []
    else:
      self.object_distance = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.object_distance)
      buff.write(_struct_I.pack(length))
      for val1 in self.object_distance:
        _x = val1.object
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.distance
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_distance is None:
        self.object_distance = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object_distance = []
      for i in range(0, length):
        val1 = yolo_object_detector.msg.StereoData()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.object = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.object = str[start:end]
        start = end
        end += 4
        (val1.distance,) = _get_struct_f().unpack(str[start:end])
        self.object_distance.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.object_distance)
      buff.write(_struct_I.pack(length))
      for val1 in self.object_distance:
        _x = val1.object
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.distance
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_distance is None:
        self.object_distance = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.object_distance = []
      for i in range(0, length):
        val1 = yolo_object_detector.msg.StereoData()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.object = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.object = str[start:end]
        start = end
        end += 4
        (val1.distance,) = _get_struct_f().unpack(str[start:end])
        self.object_distance.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
